#
# Makefile for nfc devices
#

#ifeq ($(MTK_NFC_SUPPORT),yes)
#obj-y	+= pn544.o
#else
#obj-$(CONFIG_PN544_NFC)		+= pn544.o
#endif
#pn544 drive not use this again .use the /mediatek/kernel/drivers/nfc/pn544.c
obj-n	+= pn544.o
